version: '3.8'

services:
  backend:
    build: .
    container_name: fitness-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_URL: postgresql://user:password@db:5432/fitnessdb
      JWT_SECRET: supersecretkeysupersecretkey
    volumes:
      - .:/app
    command: npm run start

  db:
    image: postgres:16
    container_name: fitness-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitnessdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
