version: '3.8'

services:
  backend:
    build: .
    container_name: fitness-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: fitnessdb
    volumes:
      - .:/app
    command: npm run dev # or npm start

  db:
    image: postgres:16
    container_name: fitness-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitnessdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
